### ISSUE TITLE
Protected and private methods.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-design#84] opened 2015-11-04 11:29 UTC
I'd like to discuss private and protected methods.

1. What are they?
2. How we define them?
3. How we document them?
4. If and how we test them?

---

1. From what I understand, general consensus right now is that, for us:
  * Protected method is a method that is used by the class and also other classes in their internal mechanisms but should not be used by users. Protected method is inherited by derived class.
  * Private method is a method used only by the class and there is no need to for it to be public, even for internal mechanisms of other classes. Something like a helper function, that wraps/organizes a part of code.

2. Both protected and private methods should start their name with underscore.
  * Since protected method has to be available for other classes we define them in class scope:
  ```javascript
  class Foo {
      /**
       * This method is protected.
       * @protected
       */
      _protectedMethod() { }
  }
  ```
  * Since we actively do not want other parts of code to use private functions, we can and should define them outside of class scope:
  ```javascript
  class Foo {
      // ...
      myFunc( a ) {
          // ...
          a = _privateMethod( a );
          // ..
      }
  }
  
  /**
   * This method is private
   * @method _privateMethod
   * @private
   */
  function _privateMethod( a ) {
      // ...
  }
  ```
3. Both protected and private methods should be taggged by an appropriate JSDoc tag (@private and @protected) and documented. We could argue that private methods are used only by the class but still they are used and might need to be expanded or used in other places so I see no reason not to document them. I am for using normaln JSDoc documentation for both protected and private methods.
4. Protected method should be tested as usual, there is no reason why we should not test them. For private methods, I hold an opinion that we don't have to test them, as they are tested by testing functions that use them. We should still get code coverage for them, even if they are not available outside (or am I wrong?).

**Comment by oleq** [comment] 2015-11-04 12:04
Yes. You're right. This also reflects the concepts which drive my existing code in v5.

Protected methods are **not** a part of a class interface but they are methods of class instances nevertheless. Mostly for
1. Convenience – to keep thing in the right `this` context, and avoid `call`/`apply`/`bind` mess, which would be a common thing if we made them all private.
2. Testing – often as a noticeable part of the class logic, they also deserve unit tests.
3. Sharing – not being a part of a class interface doesn't mean not being shared and re–used between the modules.

As for private methods, since they are available within the module's scope only, there's no need (IMO) to mark them with the leading underscore. So instead of

```
function _privateMethod( a ) {
    // ...
}
```

it's simply

```
function privateMethod( a ) {
    // ...
}
```

**Comment by jodator** [comment] 2015-11-04 12:05
Ad. 4. I'm for not testing private methods as they can be changed freely in my opinion.

**Comment by jodator** [comment] 2015-11-04 12:05
> As for private methods, since they are available within the module's scope only, there's no need (IMO) to mark them with the leading underscore. So instead of

+1

**Comment by scofalik** [comment] 2015-11-04 12:48
I kept underscore in private methods to make it clear that this is a private method when you stumble upon it in the other places of class code. But I can understand your point of view.

**Comment by pjasiun** [comment] 2015-11-04 12:48
I also like the idea of having private and protected methods and properties. This is how I understand them.

## Protected

Protected methods can be used in tests.
Protected methods can be used by child classes.
Protected methods can be used by "related" classes, classes from the same namespace, if there is no other way.

Protected methods should NOT be used by the code from other namespaces.
Protected methods should NOT be used by the code from other plugins.
Protected methods is NOT a part of the API.

Same for protected properties.

For me it was very useful to have protected `node._getAttrCount()` to use it in tests, it makes tests much better. Other example: current operations implementation is that they move nodes to the graveyard tree. They need to get the root of the graveyard from the `Document`. But we may change this mechanism one day (hope not) and there is no reason why anyone but operations should know about the graveyard existence, so the `document._graveyard` is protected: we do not want to make it public, but also it can be private if operations use it.

## Private

Private methods and properties can be used only by the class which defines it. 

Private methods and properties can NOT be used in tests.
Private methods and properties can NOT be used by child classes.
Private methods and properties can NOT be used in any other class.

It does not matter how the method or property was defined. It is sometimes simpler to define it as a class method, or as a property in the constructor. It makes code simpler. But if it is marked as `private` no one should use it and it should be treat as a scope function/property.

It was very nice to have a private property `Node.attrs` and when I changed its type from `array` to `Set` and changed access methods I got zero red tests.

**Comment by scofalik** [comment] 2015-11-04 12:51
I think we should stick to one way of defining those methods (and properties). Private property should be done like protected method / property, there is no other way around it, except of using `Symbol` and hack-y workarounds, which, IMHO, stinks.

**Comment by pjasiun** [comment] 2015-11-04 12:52
It is also very important, that, after the release we will not be able to change the public methods, but protected and private should not be used by others and we should be able to change it.

**Comment by pjasiun** [comment] 2015-11-04 13:00
In the F2F talks we agreed that since we have no other way to define private properties the same way protected are defined, private methods could be defined the same way too. Also private methods may need to use `this`.

```
class Foo {
    // ...
    /**
    * This method is private
    *
    * @private
    */
    _privateMethod() {
        // ...
    }
}
```

**Comment by scofalik** [comment] 2015-11-04 13:02
We haven't agreed to it, we just said that this is a valid argument behind this solution :)

**Comment by Reinmar** [comment] 2016-01-20 09:14
As for documenting private parts – I'm for creating JSDoc comments for properties and methods which are accessible in a class prototype or constructor, so which were defined using normal names (like `_privateMethod()`). But if they were defined using symbols or as functions outside the prototype, then it's better to use normal comments (but of course similar syntax).

In theory we shouldn't need to put any private documentation to JSDoc, but I feel that having real documentation for things that are accessible may avoid name collisions. That's also why symbols and other functions don't need to be defined as JSDoc items IMO.

**Comment by Reinmar** [comment] 2016-01-20 09:21
And one more thing – I'm for referring to symbol properties as `_symbolName`. Otherwise, we'll get crazy.

So:

```
const attributesSymbol = Symbol( 'attributes' );

// @private
// @propert _attributes
this[ attributesSymbol ] = {};

// Uses {@link #_attributes} in order to foo them.
function foo() { ...
```

**Comment by oleq** [comment] 2016-01-20 11:13
> As for documenting private parts – I'm for creating JSDoc comments for properties and methods which are accessible in a class prototype or constructor, so which were defined using normal names (like _privateMethod()). But if they were defined using symbols or as functions outside the prototype, then it's better to use normal comments (but of course similar syntax).

:+1:

**Comment by Reinmar** [comment] 2016-02-08 11:59
I documented our decisions regarding properties visibility: https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style/_compare/47e3b00c4d2b1d211c9280fce6b6840828aab9e4...563d2fd6b97b07e32bd0f59d75b1ac7d92700f35

I also confirmed that we use Java's semantics: http://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html

If there are no other comments on this I'd close this topic.

**Comment by Reinmar** [comment] 2016-02-08 12:12
And... we'll need to implement this change (removing `_` from protected method names) in the existing code...

**Comment by Reinmar** [comment] 2016-02-09 10:34
Actually, I've got a problem with this myself. I found a couple conventions but all which use any underscores use them for protected stuff as well. I guess that this is intended to easily distinguish between stuff that you can touch when using some class (from outside of it – so a typical use case) and stuff that you shouldn't. And it makes sense.

If we prefix only private stuff, then it may be confusing. Without look into the docs you won't be sure how to use some class. Especially that popular conventions state that if you use underscores at all, all non-underscored things are public.

So, I'd keep the previous convention defining that protected stuff is underscored as well. In my opinion it makes much more sense. I even started feeling that when fixing the code in ckeditor/ckeditor5-core#192, because suddenly methods which were absolutely invalid in terms of the global use looked as global.

**Comment by fredck** [comment] 2016-02-09 11:08
That's because in JavaScript, for real, there are just public and private methods. That's the one and only "popular convention".

**Comment by fredck** [comment] 2016-02-09 11:11
What I meant to say is that we're inventing this thing about protected methods, so we can do it in the way we want. I just feel that, because of that popular convention, underscore means "don't touch this thing **never**", which doesn't fit with the idea of protected methods.

**Comment by Reinmar** [comment] 2016-02-09 11:24
> "don't touch this thing never"

For a big group of developers the protected stuff shouldn't be ever touched as well. We've got two groups here:

* Those using your class from outside (for which protected == private). These guys know your class only briefly because it's just one of the components that they use. They didn't dig deep into the docs to learn how to use it – they just use it. And this is the biggest group of developers.
* Those who are subclassing your class (for which protected == public). These guys had a bigger chance to look into the docs, understand the class, learn which property comes from where, etc. And this group is much much smaller than the previous one.

Therefore, it makes much more sense to unify names of protected and private properties because for majority of developers and especially for those having a short contact with your class this convention perfectly distinguish what they can and cannot touch.

**Comment by fredck** [comment] 2016-02-09 11:38
I'm not pushing any way here... just adding lines of thought:

 * Protected methods are guaranteed to be backwards compatible. If one, by mistake, "successfully" use them, it is not a big deal. Still one has to go to the docs to know that they exist.
 * Private methods are NOT guaranteed to be backwards compatible. If one, by mistake, use them (thinking that they are protected instead), there is a bigger chance that the code will break in the future.

The above is meant to say that, although there may be a bigger audience not interested on protected methods, the impact of mistakes on the minority group may be much more important.

**Comment by Reinmar** [comment] 2016-02-18 15:11
@pjasiun seconds the idea that protected methods should be prefixed with an underscore for the same reasons I posted in the previous comment.

I'll close this issue after making sure that the wiki is up to date.

**Comment by pjasiun** [comment] 2016-02-18 15:14
:+1:

**Comment by Reinmar** [comment] 2016-03-08 13:32
I updated the wiki: https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style/_compare/a3311298070ca23b67ed57680aed0897ee5ee298...465585a6f20c6135f53bb2696ed7d252ff7e3c42

**Closed** 2016-03-08 13:33 UTC
